/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class performance_PerformancePrint */

#ifndef _Included_performance_PerformancePrint
#define _Included_performance_PerformancePrint
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     performance_PerformancePrint
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_performance_PerformancePrint_printHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
