/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class performance_CacheID */

#ifndef _Included_performance_CacheID
#define _Included_performance_CacheID
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     performance_CacheID
 * Method:    callStaticMethod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_performance_CacheID_callStaticMethod
  (JNIEnv *, jclass, jint);

/*
 * Class:     performance_CacheID
 * Method:    callStaticMethodWithCache
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_performance_CacheID_callStaticMethodWithCache
  (JNIEnv *, jclass, jint);

/*
 * Class:     performance_CacheID
 * Method:    callSum
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_performance_CacheID_callSum
  (JNIEnv *, jobject);

/*
 * Class:     performance_CacheID
 * Method:    callSumWithCache
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_performance_CacheID_callSumWithCache
  (JNIEnv *, jobject);

/*
 * Class:     performance_CacheID
 * Method:    callSumPrimitive
 * Signature: (IIIIII)I
 */
JNIEXPORT jint JNICALL Java_performance_CacheID_callSumPrimitive
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
